version: '3.8'

services:
  labelimg:
    build: .
    image: labelimg:latest
    container_name: labelimg
    user: "${UID}:${GID}"  # Add this line
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - LIBGL_ALWAYS_INDIRECT=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./test_images:/app/test_images
    working_dir: /app
    stdin_open: true
    tty: true
    network_mode: host
    command: labelImg